# Generated by Django 3.0.8 on 2020-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='kitchen',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
