# Generated by Django 3.0.8 on 2020-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
