name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.84ba4061-5bf5-49ed-89fc-9275eac58572}}
          heroku_app_name: "neproom" #Must be unique in Heroku
          heroku_email: "keskhanal2413@gmail.com"